/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef IDIFF_PRIVATE_H
#define IDIFF_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"-2.-4.-8.-16"
#define VER_MAJOR	-2
#define VER_MINOR	-4
#define VER_RELEASE	-8
#define VER_BUILD	-16
#define COMPANY_NAME	""
#define FILE_VERSION	""
#define FILE_DESCRIPTION	""
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	""
#define PRODUCT_VERSION	""

#endif /*IDIFF_PRIVATE_H*/
